path_dataset: data\raw\YoutubeCommentsDataSet.csv

path_train_set:
- data\internim\X_test.pkl
- data\internim\y_train.pkl
path_test_set:
- data\internim\X_train.pkl
- data\internim\y_test.pkl

Word_Column :
- Comment

label :
- Sentiment